path: 'E:\Projects\helmet_detector\data' # dataset root dir
train: images  # train images (relative to 'path')
val: images  # val images (relative to 'path')

# Classes
names:
  0: With helmet
  1: Without helmet 